# Generated by Django 3.1.7 on 2021-05-01 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=128, unique=True, verbose_name='地名')),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=128, verbose_name='位置（一等、二等...）')),
            ],
        ),
        migrations.CreateModel(
            name='TrainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128, unique=True, verbose_name='车次类型名')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发时间')),
                ('arrive_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='到达时间')),
                ('arrive_type', models.CharField(default='正点', max_length=128, verbose_name='正点/晚点')),
                ('position_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_manage.positiontype', verbose_name='位置类型')),
                ('start_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_manage.placetype', verbose_name='出发地')),
                ('train_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_manage.traintype', verbose_name='车次类型')),
            ],
        ),
    ]
