# Generated by Django 3.1.7 on 2021-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manage', '0006_auto_20210524_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dong_wo',
            field=models.IntegerField(default=0, verbose_name='动卧'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='er_deng',
            field=models.IntegerField(default=0, verbose_name='二等座'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gao_ji_ruan_wo',
            field=models.IntegerField(default=0, verbose_name='高级软卧'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qi_ta',
            field=models.IntegerField(default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ruan_zuo',
            field=models.IntegerField(default=0, verbose_name='软座'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='shang_wu',
            field=models.IntegerField(default=0, verbose_name='商务座'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='wu_zuo',
            field=models.IntegerField(default=0, verbose_name='无座'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='yi_deng',
            field=models.IntegerField(default=0, verbose_name='一等座'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ying_wo',
            field=models.IntegerField(default=0, verbose_name='硬卧'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ying_zuo',
            field=models.IntegerField(default=0, verbose_name='硬座'),
        ),
    ]
