# Generated by Django 3.1.7 on 2021-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(default=1, verbose_name='用户类型（0.超级管理员 99 普通用户）'),
            preserve_default=False,
        ),
    ]
