# Generated by Django 3.1.7 on 2021-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(default=99, verbose_name='用户类型（0.超级管理员 99 普通用户）'),
        ),
    ]
