# Generated by Django 3.1.7 on 2021-05-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210501_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=1, max_length=128, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=1, max_length=32, verbose_name='真实姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_img_url',
            field=models.CharField(default=1, max_length=512, verbose_name='用户头像地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal',
            field=models.CharField(default=1, max_length=4096, verbose_name='个人简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=1, max_length=16, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default=1, max_length=4, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
