# Generated by Django 3.1.7 on 2021-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210502_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='小鬼', max_length=128, verbose_name='昵称'),
        ),
    ]
